server:
  port: 5557
spring:
  application:
    name: rocketmq-exporter
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  config: classpath:logback.xml

rocketmq:
  config:
    webTelemetryPath: ${WEB_TELEMETRY_PATH}
    rocketmqVersion: V4_3_2
    namesrvAddr: ${NAMESRV_ADDR}
    enableCollect: true

threadpool:
  collect-client-metric-executor:
    core-pool-size: 10
    maximum-pool-size: 10
    keep-alive-time: 3000
    queueSize: 5000
task:
  count: 5 # num of scheduled-tasks
  collectTopicOffset:
    cron: 15 0/1 * * * ?
  collectConsumerOffset:
    cron: 15 0/1 * * * ?
  collectBrokerStatsTopic:
    cron: 15 0/1 * * * ?
  collectBrokerStats:
    cron: 15 0/1 * * * ?
  collectBrokerRuntimeStats:
    cron: 15 0/1 * * * ?
