apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rocketmq-operator.fullname" . }}
  labels:
  {{- include "rocketmq-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.rocketmqOperator.serviceAccount.annotations | nindent 4 }}