// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetaService) DeepCopyInto(out *MetaService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetaService.
func (in *MetaService) DeepCopy() *MetaService {
	if in == nil {
		return nil
	}
	out := new(MetaService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MetaService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetaServiceList) DeepCopyInto(out *MetaServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MetaService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetaServiceList.
func (in *MetaServiceList) DeepCopy() *MetaServiceList {
	if in == nil {
		return nil
	}
	out := new(MetaServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetaServiceSpec) DeepCopyInto(out *MetaServiceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetaServiceSpec.
func (in *MetaServiceSpec) DeepCopy() *MetaServiceSpec {
	if in == nil {
		return nil
	}
	out := new(MetaServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetaServiceStatus) DeepCopyInto(out *MetaServiceStatus) {
	*out = *in
	if in.MetaServers != nil {
		in, out := &in.MetaServers, &out.MetaServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetaServiceStatus.
func (in *MetaServiceStatus) DeepCopy() *MetaServiceStatus {
	if in == nil {
		return nil
	}
	out := new(MetaServiceStatus)
	in.DeepCopyInto(out)
	return out
}
