apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rocketmqs.rocketmq.apache.org
spec:
  group: rocketmq.apache.org
  names:
    kind: Rocketmq
    listKind: RocketmqList
    plural: rocketmqs
    singular: rocketmq
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: "APIVersion defines the versioned schema of this representation
                                    of an object. Servers should convert recognized schemas to the latest
                                    internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources"
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
                                   object represents. Servers may infer this from the endpoint the client
                                   submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            broker:
              description: Broker defines rocketmq broker spec info
              type: object
            nameService:
              description: NameService defines rocketmq name service spec info
              type: object
            console:
              description: Console defines rocketmq console deployment info
              type: object
        status:
          properties:
            nameService:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
                NameService is the name of name service'
              type: string
            broker:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
                Brokers is the name of broker'
              type: string
          required:
            - nameService
            - broker
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
