name: E2E tests

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  test:
    name: ${{ matrix.testpath }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testpath:
          - ./tests/e2e/v1alpha1/setup/

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Dockerfile
      run: docker build . --file Dockerfile --tag rocketmq-operator:e2e

    - name: Install Chainsaw
      uses: kyverno/action-install-chainsaw@v0.1.0

    - name: Check install
      run: chainsaw version

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.5.0
      with:
        config: tests/_config/kind-config.yaml
        cluster_name: kind

    - name: Load Docker image into Kind
      run: | 
        kubectl cluster-info --context kind-kind
        kind load docker-image rocketmq-operator:e2e --name kind

    - name: Install RocketMQ Operator
      run: |
        make deploy
        kubectl set image deployment/rocketmq-operator manager=rocketmq-operator:e2e -n default

    - name: Wait for RocketMQ Operator to be ready
      run: |
        kubectl wait --for=condition=available --timeout=300s deployment/rocketmq-operator -n default
  
    - name: Run chainsaw test
      run: chainsaw test --test-dir ${{ matrix.testpath }} --config tests/_config/chainsaw-configuration.yaml
